"""Configuration for the public SQLite-backed dashboard."""

from __future__ import annotations

import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
SQLITE_DIR = DATA_DIR / "sqlite"
RAW_API_DIR = DATA_DIR / "raw_api"
LOG_DIR = DATA_DIR / "logs"

DB_PATH = os.getenv('DB_PATH', 'data/sqlite/ipl.db')
DEFAULT_IPL_CSV_PATH = RAW_DATA_DIR / "IPL.csv"

BALL_BY_BALL_RAW_COLUMNS = [
    "id",
    "match_id",
    "date",
    "match_type",
    "event_name",
    "innings",
    "batting_team",
    "bowling_team",
    "over",
    "ball",
    "ball_no",
    "batter",
    "bat_pos",
    "runs_batter",
    "balls_faced",
    "bowler",
    "valid_ball",
    "runs_extras",
    "runs_total",
    "runs_bowler",
    "runs_not_boundary",
    "extra_type",
    "non_striker",
    "non_striker_pos",
    "wicket_kind",
    "player_out",
    "fielders",
    "runs_target",
    "review_batter",
    "team_reviewed",
    "review_decision",
    "umpire",
    "umpires_call",
    "player_of_match",
    "match_won_by",
    "win_outcome",
    "toss_winner",
    "toss_decision",
    "venue",
    "city",
    "day",
    "month",
    "year",
    "season",
    "gender",
    "team_type",
    "superover_winner",
    "result_type",
    "method",
    "balls_per_over",
    "overs",
    "event_match_no",
    "stage",
    "match_number",
    "team_runs",
    "team_balls",
    "team_wicket",
    "new_batter",
    "batter_runs",
    "batter_balls",
    "bowler_wicket",
    "batting_partners",
    "next_batter",
    "striker_out",
]
BALL_BY_BALL_DERIVED_COLUMNS = [
    "run_rate",
    "required_runs",
    "balls_remaining",
    "wickets_remaining",
    "required_run_rate",
    "powerplay_balls_remaining",
    "middle_balls_remaining",
    "death_balls_remaining",
    "wicket_taken",
    "batter_espn_athlete_id",
    "bowler_espn_athlete_id",
    "player_out_espn_athlete_id",
    "player_of_match_espn_athlete_id",
    "batter_player_id",
    "bowler_player_id",
    "player_out_player_id",
    "player_of_match_player_id",
    "batter_canonical_name",
    "bowler_canonical_name",
    "player_out_canonical_name",
    "player_of_match_canonical_name",
]
BALL_BY_BALL_BASE_COLUMNS = BALL_BY_BALL_RAW_COLUMNS + BALL_BY_BALL_DERIVED_COLUMNS
BALL_BY_BALL_HELPER_COLUMNS = ["ball_id", "source", "ingest_run_id", "created_at", "updated_at"]

MATCH_LIST_BASE_COLUMNS = [
    "match_id",
    "date",
    "bat_first",
    "bowl_first",
    "player_of_match",
    "match_won_by",
    "win_outcome",
    "toss_winner",
    "toss_decision",
    "venue",
    "city",
    "year",
    "superover_winner",
    "result_type",
    "method",
    "event_match_no",
    "stage",
    "playoff_match",
    "first_innings_runs",
    "first_innings_wickets",
    "first_innings_balls",
    "first_innings_run_rate",
    "first_innings_balls_adj",
    "first_innings_powerplay_balls",
    "first_innings_middle_balls",
    "first_innings_death_balls",
    "first_innings_powerplay_runs",
    "first_innings_powerplay_wicket",
    "first_innings_middle_runs",
    "first_innings_middle_wicket",
    "first_innings_death_runs",
    "first_innings_death_wicket",
    "second_innings_runs",
    "second_innings_wickets",
    "second_innings_balls",
    "second_innings_run_rate",
    "second_innings_balls_adj",
    "second_innings_powerplay_balls",
    "second_innings_middle_balls",
    "second_innings_death_balls",
    "second_innings_powerplay_runs",
    "second_innings_powerplay_wicket",
    "second_innings_middle_runs",
    "second_innings_middle_wicket",
    "second_innings_death_runs",
    "second_innings_death_wicket",
    "batting_team_won",
    "bowling_team_won",
    "batting_team_won_toss",
    "bowling_team_won_toss",
    "batting_team_NRR",
    "bowling_team_NRR",
]
MATCH_LIST_HELPER_COLUMNS = [
    "source",
    "status",
    "status_detail",
    "ingestion_status",
    "completeness_status",
    "data_quality_flag",
    "last_successful_fetch_ts",
    "last_consistency_check_ts",
    "created_at",
    "updated_at",
]

MATCH_SCHEDULE_COLUMNS = [
    "match_id",
    "season",
    "competition",
    "match_date",
    "scheduled_start_ts",
    "actual_start_ts",
    "status",
    "status_detail",
    "team1",
    "team2",
    "venue",
    "city",
    "event_match_no",
    "stage",
    "source",
    "ingestion_status",
    "last_successful_fetch_ts",
    "created_at",
    "updated_at",
]
